defaults:
  - flame_h2c_lora
  - _self_

exp_name: flame_h2c_lora_rot_geo_500
max_epochs: 500

logging:
  wandb:
    enabled: True
    project: "vggt-h2c"
    name: ${exp_name}
    id: ${exp_name}
    resume: True
    tags: ["lora", "vggt-1b", "quaternion", "relative-h2c", "rotation-geodesic", "old-translation-loss"]
    notes: "Relative H2C for 500 epochs with original translation supervision and geodesic rotation loss"
    mode: "offline"
    dir: ${logging.log_dir}/wandb
  pose_visual_frequency:
    train: 0
    val: 25
  visuals_save_dir: "${exp_name}/visualizations"

loss:
  camera:
    weight_trans: 1.0
    weight_trans_dir: 0.0
    weight_trans_log_norm: 0.0
    weight_reproj: 0.0
    weight_rot: 1.0
    weight_focal: 0.5
    rotation_loss_type: "geodesic"
